export const ADD_FEATURED = "ADD_FEATURED";
export const FEATURED_FAILED = "FEATURED_FAILED";
export const FEATURES_LOADING = "FEATURES_LOADING";


export const ADD_USER = "ADD_USER";
export const USER_ADD_FAILED = "USER_ADD_FAILED";

export const GET_REGISTERED_USERS = "GET_REGISTERED_USERS";
export const GET_REGISTERED_USERS_FAILED = "GET_REGISTERED_USERS_FAILED";

export const HIDE_OK_MODAL = "HIDE_OK_MODAL";
export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const SET_LOGIN_USER_DATA = "SET_LOGIN_USER_DATA";

export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const FEEDBACK_LOADING = "FEEDBACK_LOADING";
export const FEEDBACK_FAILED = "FEEDBACK_FAILED";

export const SET_SELECTED_FOOD = "SET_SELECTED_FOOD";

export const ADD_ORDER = "ADD_ORDER";

export const ADD_FOOD_TO_CART = "ADD_FOOD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
